# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticketid', models.CharField(max_length=265)),
                ('Dateofjourney', models.CharField(max_length=265)),
                ('Sheduletime', models.CharField(max_length=265)),
                ('Source', models.CharField(max_length=265)),
                ('Dcestination', models.CharField(max_length=265)),
                ('Phonenumber', models.CharField(max_length=265)),
                ('Status', models.CharField(max_length=265)),
            ],
        ),
    ]
