# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoextr', '0002_auto_20171203_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='Ticketid',
            field=models.CharField(max_length=265, primary_key=True, serialize=False),
        ),
    ]
